sudo: required
dist: trusty
group: edge

language: go
go:
  - 1.5.2
env:
  - GOARCH=amd64
gobuild_args:

# adds support for java, to release the monitors-library  
addons:
  apt:
    packages:
      - oracle-java7-installer

# whitelist
branches:
  only:
    - dev
  except:
    - v-dev

cache:
  directories:
    - /usr/bin

before_install:
  - go get github.com/tools/godep
  # Attempt to fix for java 7: https://github.com/travis-ci/travis-ci/issues/5545
  # reference: http://stevenschwenke.de/cannotFindSymbolInTravisAndShippable
  - export JAVA_HOME="/usr/lib/jvm/java-7-oracle"
  - export PATH="$PATH:/usr/lib/jvm/java-7-oracle/bin"
  - export java_path="/usr/lib/jvm/java-7-oracle/jre/bin/java"
  - update-alternatives --set java $java_path
  - java -version

# test that the services and the library build correclty
install: 
  - make all

# test that the image correclty build
script: make build_container

cache:
  directories:
    - $HOME/.m2
    - /usr/bin

before_deploy:
  # Clean the v-dev release and tag we are using to release development version in CI
  - sudo wget https://github.com/benchflow/benchflow/raw/dev/ci/clean_v-dev_release.sh -O /usr/bin/clean_v-dev_release.sh
  - sudo chmod +x /usr/bin/clean_v-dev_release.sh
  - export REPO_NAME=monitors
  - /usr/bin/clean_v-dev_release.sh

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_ACCESS_TOKEN
  file: 
    - environment/cpu/bin/cpu
    - dbms/sqlquery/mysql/bin/querymysql
    - target/benchflow-monitors-driver-library.jar
  skip_cleanup: true
  on:
    tags: false
    repo: benchflow/monitors
    branch: dev
