FROM benchflow/base-images:dev

MAINTAINER Vincenzo FERME <info@vincenzoferme.it>

COPY ./bin/cpu_linux /app/cpu
RUN chmod +x /app/cpu
#TODO: change back, changed for testing purposes
#COPY ./services/300-cpu-monitor.conf /apps/chaperone.d/300-cpu-monitor.conf
CMD /app/cpu
 
EXPOSE 8080
